source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'Masonry'
pod 'MBProgressHUD'
pod 'Bugly'
pod 'IQKeyboardManager'
pod 'SDWebImage'
#pod 'MJRefresh'
#pod 'AFNetworking', '~> 3.0'
#pod 'AFNetworking', '~> 3.0'
#pod 'UPYUN', '~> 1.0.0'
pod 'UMengSocial', '~> 4.3'
pod 'UMengAnalytics-NO-IDFA'
pod 'UMengFeedback', '~> 2.3.4'
pod 'RongCloudIMKit'
pod 'SVPullToRefresh'