source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'Masonry'
pod 'MBProgressHUD'
pod 'Bugly'
pod 'IQKeyboardManager'
pod 'SDWebImage'
pod 'SVPullToRefresh'
pod 'SDCAlertView', '2.5.4' # SDCAlertView -- 2.5.4 支持iOS7
pod 'MarqueeLabel'
pod 'iVersion'
pod 'UMengSocial', '~> 4.3'
pod 'UMengAnalytics-NO-IDFA'
pod 'UMengFeedback', '~> 2.3.4'
pod 'RongCloudIMKit'
pod 'BlocksKit'
pod 'TMCache'

#pod 'FlatUIKit'
#pod 'TTTAttributedLabel'

#pod 'TPKeyboardAvoiding', '1.2.4'
#pod 'MJRefresh'
#pod 'AFNetworking', '~> 3.0'
#pod 'UPYUN', '~> 1.0.0'